### ISSUE TITLE
Deployment of ml-pipeline with Kubeflow pipeline version 1.0.3 with IAM role is not working.

### ISSUE THREAD

**Issue by amit043** [e2fyi/kubeflow-aws#18]
when I run the command .
kubectl kustomize overlay/${VARIANT} > kubeflow-pipelines-aws.yaml

I got the config merge issue.

I1027 20:05:10.994651   40204 log.go:172] well-defined vars that were never replaced: mlmdDb,pipelinePath,awsIAMAnnotationKey,dbHost,dbPort,kfp-app-name,kfp-app-version,artifactRepositoryKeyPrefix,groupConcatMaxLen,kfp-namespace,mysqlStorageType,cacheDb,kfp-container-runtime-executor,mysqlPvcName,mysqlStorageSize,pipelineDb,artifactRepositoryBucket,awsIAMRole,awsRegion,kfp-artifact-bucket-name,mysqlStorageClass
Error: 80 is expected to be string

**Comment by eterna2** [comment]
ok let me have a look

**Comment by eterna2** [comment]
@amit043 

Seems to be an issue with `kustomize`. I fixed it by remove the permission to patch `service/ports/port` (i.e. u can't modify the ports for service resources in the downstream overlay).

It has been quite some time since I written the manifest, I am asking my friend to review the change before merging to master.

Meanwhile u can refer to my PR #19 branch.
